#!/bin/bash
# References for common Arch Linux package management tasks

# Display usage if no parameters given
if [[ -z $@ ]]; then
  echo " ${0##*/} <option> <*package> - pacman management tasks:
   1 | oneshot  - install package(s) as a dependency
   c | clean    - cleans package cache of packages no longer installed
   d | depclean - remove dependencies no longer used
   e | explicit - force package to be recognized as necessary
   f | forcerem - force remove package (no dependency check)
   i | install  - install a package
   l | list     - list files installed by the package
   o | owns     - package that owns a file
   n | info     - information about the package
   p | local    - install package locally (a pkg.tar.gz file)
   q | query    - query for an installed package (Q for details)
   r | remove   - remove a package
   s | search   - search for a package
   u | upgrade  - sync database and upgrade system
   y | sync     - sync database
   ---
   optimize     - optimize database by placing files in order on disk
   pkglist      - create list of official and local installed packages
   ---"
   exit
fi

case $1 in
  1 | oneshot )   shift
                  if [[ "${1#*.pkg.}" == tar.gz ]]; then
                    sudo pacman -U --asdeps "$@"
                  else
                    yaourt -S --asdeps "$@"
                  fi
                  ;;
  c | clean )     sudo pacman -Sc
                  ;;
  d | depclean )  sudo pacman -Rs $(yaourt -Qtdq)
                  ;;
  e | explicit )  shift
                  sudo pacman -S --asexplicit "$@"
                  ;;
  f | forcerem )  shift
                  sudo pacman -Rcd "$@"
                  ;;
  i | install )   shift
                  #if [ -f /var/cache/pacman-local/"$arg".pkg.tar.gz ]; then
                    ## Check from AUR to find latest version
                    ##  use aurtar script and curl to get ver#
                    #for arg in "$@"; do
                    # if [ -f /var/cache/pacman-local/pkg/"$arg"*.pkg.tar.gz ]
                    #  then
                    # pacman -U /var/cache/pacman-local/pkg/"$arg"*.pkg.tar.gz
                    #  else
                    #  packer -S "$@"
                    #  fi
                    #done
                    #packer -S "$@"
                    sudo -E packer -S "$@"
                  #fi
                  ;;
  l | list )      shift
                  pacman -Qql "$@"
                  ;;
  o | own )       shift
                  pacman -Qo "$@"
                  ;;
  p | local )     shift
                  sudo pacman -U "$@"
                  ;;
  n | info )      shift
                  for arg in "$@"; do
                    packer -Si $arg
                  done
                  ;;
  q | query )     shift
                  pacman -Qqs  "$@"
                  ;;
  Q | Query )     shift
                  pacman -Qs  "$@"
                  ;;
  r | remove )    shift
                  # http://tinyurl.com/pacman-Rcs
                  # sudo pacman -Rs "$@"
                  sudo pacman -Rcs "$@"
                  ;;
  s | search )    shift
                  packer -Ss "$@"
                  ;;
  u | upgrade )   sudo -E packer -Syu #--noconfirm
                  ;;
  y | sync )      shift
                  sudo pacman -Syy
                  ;;
  # ---
  optimize )      sudo pacman-optimize
                  ;;
  pkglist )       date="$(date "+%F")"
                  pacman -Qqe | grep -v "$(pacman -Qqm)" > pkglist-off-$date.txt
                  pacman -Qqm >                            pkglist-loc-$date.txt
                  ;;
  * )             sudo pacman "$@"
esac
