#!/bin/bash

# Rename files in correct order using zero padding
# http://www.unix.com/shell-programming-scripting/132557-zero-padding-while-renaming-files.html

pre=1
cnt=1

for file in *
  do
    if [ -f "$file" ]; then
      ext=${file##*.}
      printf -v pad "%07d" "$cnt"
      mv "$file" "${pre}${pad}"
      cnt=$(( $cnt + 1 ))
    fi
  done
exit 0
