#!/bin/bash
# Take screenshot of X desktop from console


# Text color variables
txtund=$(tput sgr 0 1)          # Underline
txtbld=$(tput bold)             # Bold
bldred=${txtbld}$(tput setaf 1) #  red
bldblu=${txtbld}$(tput setaf 4) #  blue
bldwht=${txtbld}$(tput setaf 7) #  white
txtrst=$(tput sgr0)             # Reset
info=${bldwht}*${txtrst}        # Feedback
pass=${bldblu}*${txtrst}
warn=${bldred}!${txtrst}

# Display usage if no parameters given
if [[ -z "$@" ]]; then
  echo " ${0##*/} <screenshot-name>.png - take screenshot of X desktop from console"
  exit
fi

chvt 7; sleep 10 ; import -display :0.0 -window root "$1".png && \
echo "$pass Screenshot taken of X desktop:" && \
echo "$pass ${txtund}"$1".png${txtrst}."
