#!/bin/bash
# Paste contents of clipboard to file in terminal.

# Text color variables
txtund=$(tput sgr 0 1)          # Underline
txtbld=$(tput bold)             # Bold
bldred=${txtbld}$(tput setaf 1) #  red
bldblu=${txtbld}$(tput setaf 4) #  blue
bldwht=${txtbld}$(tput setaf 7) #  white
txtrst=$(tput sgr0)             # Reset
info=${bldwht}*${txtrst}        # Feedback
pass=${bldblu}*${txtrst}
warn=${bldred}!${txtrst}

filename=$@
pasteinfo="clipboard contents"

# Display usage if no parameters given
if [[ -z $filename ]]; then
  echo " ${0##*/} <filename> - paste contents of context-menu clipboard to file"
  exit
fi

# if filename matches a directory name exit
if [ -d "$filename" ]; then
  echo "$warn Directory already has the name ${txtund}"${filename##*/}"${txtrst}"
  exit
fi

# check if file exists, prompt to append or override, else create new
if [[ -f $filename ]]; then
  echo "$warn File ${txtund}${filename##*/}${txtrst} already exists - (${txtbld}e${txtrst})xit, (${txtbld}a${txtrst})ppend, (${txtbld}o${txtrst})verwrite: "
  read edit
  case "$edit" in
    [aA] )  xclip -out -selection clipboard >> $filename
            echo "$pass File ${txtund}$filename${txtrst} appended with clipboard contents"
            ;;
    [oO] )  xclip -out -selection clipboard > $filename
            echo "$pass File ${txtund}$filename${txtrst} overwrote with clipboard contents"
            ;;
    * )     exit
    esac; else
    xclip -out -selection clipboard >> $filename
    echo "$pass File ${txtund}"$filename"${txtrst} created with clipboard contents"
fi
