#!/bin/bash
# crush - archive and compress file/folder(s)

# Text color variables
txtund=$(tput sgr 0 1)          # Underline
txtbld=$(tput bold)             # Bold
bldred=${txtbld}$(tput setaf 1) #  red
bldblu=${txtbld}$(tput setaf 4) #  blue
bldwht=${txtbld}$(tput setaf 7) #  white
txtrst=$(tput sgr0)             # Reset
info=${bldwht}*${txtrst}        # Feedback
pass=${bldblu}*${txtrst}
warn=${bldred}*${txtrst}

# Display usage if no parameters given
if [[ -z $@ ]]; then
  echo " crush <file> <*folder>... <*archive-name>.tar.gz - archive files/folders"
  exit
fi

# Extract last parameter (archive filename) from array and assign variable
lastparam="${!#}"

# Remove last paramerter (archive filename) for file/folder list variable
length=$(($#-1))
firstparams=${@:1:$length}

# Check if files exists first, then archive them.
if [[ ! -e $lastparam ]]; then
  for exist in $firstparams; do
    if [[ ! -e $exist ]]; then
      echo "$warn File/directory ${txtund}$exist${txtrst} does not exist."
      exit
    fi
  done
  tar -czvpf "$lastparam".tar.gz $firstparams
else
  for exist in $@; do
    if [[ ! -e $exist ]]; then
      echo "$warn File/directory ${txtund}$exist${txtrst} does not exist."
      exit
    fi
  done
  tar -czvpf "$lastparam".tar.gz $@
fi

if [ -f $lastparam.tar.gz ]; then
  echo "$pass Created archive ${bldred}$lastparam.tar.gz${txtrst}"
fi
