#!/bin/bash
# Extract common file formats

# Display usage if no parameters given
if [[ -z "$@" ]]; then
  echo " ${0##*/} <archive> - extract common file formats)"
  exit
fi

# Program(s) required
progs_req=(7z unrar unzip)
for p in ${progs_req[@]}; do
  hash "$p" 2>&- || \
  { echo >&2 " Program required \"$p\" not installed."; exit 1; }
done

# Test if file(s) exists
for f in $@; do
  if [ ! -f "$@" ]; then
    echo "File non-exist: "$f"" && file_non=y
  fi
done; [ $file_non = y ] && exit 1

# Extract file by using extension as reference
case "$@" in
  *.7z      ) 7z  x       "$@"                ;;
  *.tar.bz2 ) tar xvjf    "$@"                ;;
  *.bz2     ) bunzip2     "$@"                ;;
  *.deb     ) ar  vx      "$@"                ;;
  *.tar.gz  ) tar xvf     "$@"                ;;
  *.gz      ) gunzip      "$@"                ;;
  *.tar     ) tar xvf     "$@"                ;;
  *.tbz2    ) tar xvjf    "$@"                ;;
  *.tar.xz  ) tar xvf     "$@"                ;;
  *.tgz     ) tar xvzf    "$@"                ;;
  *.rar     ) unrar x     "$@"                ;;
  #*.rar     ) 7z  x       "$@"                ;;
  #*.zip     ) unzip       "$@"                ;;
  *.zip     ) bsdtar      "$@"                ;;
  *.Z       ) uncompress  "$@"                ;;
  *         ) echo " Unsupported file format" ;;
esac
