#!/bin/bash

MAC=`(date; cat /proc/interrupts) | md5sum | sed -r 's/^(.{10}).*$/\1/; s/([0-9a-f]{2})/\1:/g; s/:$//;'`

lladdr=$(printf "%.2x:" $((($RANDOM % 256) & 252)); for _i in 1 2 3 4;
do printf "%.2x:" $(($RANDOM % 256)); done; printf "%.2x" $(($RANDOM
% 256)))

ifconfig eth0 down
ifconfig eth0 hw ether $MAC
ifconfig eth0 up
#/etc/init.d/net.eth0 restart &> /dev/null &&
echo "eth0 up"
dhcpcd -k eth0
dhcpcd eth0
