#!/bin/bash
# Display the top five applications memory users
# http://www.cyberciti.biz/faq/linux-check-memory-usage/#comment-51021

while read command percent rss; do if [[ "${command}" != "COMMAND" ]]; then rss="$(bc <<< "scale=2;${rss}/1024")"; fi; printf "%-26s%-8s%s\n" "${command}" "${percent}" "${rss}"; done < <(ps -A --sort -rss -o comm,pmem,rss | head -n 10)
#ps -A -ao rss,comm | sort -rn | sed -n '1,5{s/^/\t/;s/ /\t/p}'
#echo " Memory (KB) "
#ps -A -ao rss,comm | sort -rn | sed -n '1,5{s/^/ /p}'

